In [5]:
print('hello')

hello


In [17]:
def addfive(a):
    return a+5
addfive(5)

10

In [30]:
def addfive(a):
    return a+5
lst = [1,2,3]
map(addfive, lst)
#print(dic)

In [32]:
print("Hello"[2:5])

llo


In [33]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, items))

TypeError: 'list' object is not callable

In [38]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.google.com'
r = requests.get(url)

In [37]:
print(r)

<Response [200]>


In [47]:
html = r.content

In [41]:
print(html)

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="dQzYwDDaQNY3gMrKH8UQGA==">(function(){window.google={kEI:'gtzVW6uaEoWotQX0yqWgDg',kEXPI:'0,18167,1335580,57,1653,305,583,714,335,790,698,527,730,143,186,106,337,213,512,21,281,29,81,444,171,131,71,256,38,43,103,30,74,2336883,197,32,302989,26305,1294,12383,4855,32691,15248,867,316,8616,1829,1402,5281,1100,3335,2,2,1848,2761,2192,363,1218,2102,2314,3191,224,887,130,1195,266,5107,575,835,284,2,579,727,606,1826,58,2,1,3,61,1236,284,1428,2611,2096,658,636,9,301,1267,222,552,1232,883,13

In [42]:
soup = BeautifulSoup(html,'lxml')

In [43]:
print(soup)

<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"/><meta content="noodp" name="robots"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"/><title>Google</title><script nonce="dQzYwDDaQNY3gMrKH8UQGA==">(function(){window.google={kEI:'gtzVW6uaEoWotQX0yqWgDg',kEXPI:'0,18167,1335580,57,1653,305,583,714,335,790,698,527,730,143,186,106,337,213,512,21,281,29,81,444,171,131,71,256,38,43,103,30,74,2336883,197,32,302989,26305,1294,12383,4855,32691,15248,867,316,8616,1829,1402,5281,1100,3335,2,2,1848,2761,2192,363,1218,2102,2314,3191,224,887,130,1195,266,5107,575,835,284,2,579,727,606,1826,58,2,1,3,61,1236,284,1428,2611,2096,658,636,9,301,1267,222,552,1232,8

In [48]:
title = soup.find('title')
print(title)

<title>Google</title>


In [46]:
title = soup.find('location')
print(title)

None


In [53]:
#Web scrapping using BeautifulSoup

import requests
from bs4 import BeautifulSoup

url = 'https://www.google.com'
r = requests.get(url)

if r.status_code == 200:
    html = r.text
    soup = BeautifulSoup(html, 'lxml')
    title = soup.find('title')
    if title is not None:
        title_text = title.text.strip()
        print(title_text)

Google


In [4]:
s = "welcome to Jupyter Notebook"
v = ['a','e','i','o','u','A','E','I','O','U']
sum([1  for char in s if char in v])

10

In [8]:
-asdf-

SyntaxError: invalid syntax (<ipython-input-8-5bbc89318c2a>, line 1)

In [55]:
import numpy as np

In [56]:
vec = [1,2,3]
np_vec = np.array(vec)

In [57]:
print(np_vec)

[1 2 3]


In [58]:
type(np_vec)

numpy.ndarray

In [11]:
import numpy as np

x = np.array([[3.2, 7.8, 9.2],
             [4.5, 9.1, 1.2]], dtype='int64')
print(x[0].itemsize)

8


In [59]:
vec2 = [[1,2,3],[4,5,6]]
np_vec2 = np.array(vec2)
print(np_vec2)

[[1 2 3]
 [4 5 6]]


In [1]:
np.Zeros()

NameError: name 'np' is not defined

### np.Zeros(3)

In [63]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [64]:
np.Zeros()

AttributeError: module 'numpy' has no attribute 'Zeros'

In [65]:
np.Zeros(3)

AttributeError: module 'numpy' has no attribute 'Zeros'

In [66]:
np.zeros(3)

array([0., 0., 0.])

In [67]:
np.zeros(3,4)

TypeError: data type not understood

In [69]:
#takes tuple as input(rows,col)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((2,3), fill_value = 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [73]:
#takes only integer as input
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.random.randint(4,50,6)

array([48, 26, 25, 13, 20, 48])

In [78]:
range(5)

range(0, 5)

In [81]:
a = range(5)
print(a)

range(0, 5)


In [82]:
# for 3 to 12 with a space off 2 exclude 12
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

In [84]:
# to generate 4 number between 3 and 5.. defual is 50
np.linspace(3,5,4)

array([3.        , 3.04081633, 3.08163265, 3.12244898, 3.16326531,
       3.20408163, 3.24489796, 3.28571429, 3.32653061, 3.36734694,
       3.40816327, 3.44897959, 3.48979592, 3.53061224, 3.57142857,
       3.6122449 , 3.65306122, 3.69387755, 3.73469388, 3.7755102 ,
       3.81632653, 3.85714286, 3.89795918, 3.93877551, 3.97959184,
       4.02040816, 4.06122449, 4.10204082, 4.14285714, 4.18367347,
       4.2244898 , 4.26530612, 4.30612245, 4.34693878, 4.3877551 ,
       4.42857143, 4.46938776, 4.51020408, 4.55102041, 4.59183673,
       4.63265306, 4.67346939, 4.71428571, 4.75510204, 4.79591837,
       4.83673469, 4.87755102, 4.91836735, 4.95918367, 5.        ])

In [17]:
np.linspace(1,100,20, endpoint=False,retstep=True)

(array([ 1.  ,  5.95, 10.9 , 15.85, 20.8 , 25.75, 30.7 , 35.65, 40.6 ,
        45.55, 50.5 , 55.45, 60.4 , 65.35, 70.3 , 75.25, 80.2 , 85.15,
        90.1 , 95.05]), 4.95)

In [30]:
np.random.randint(5,10,2)

array([8, 9])

In [83]:
x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [33]:
np.random.random(3)

array([0.09399964, 0.14396104, 0.87404038])

In [32]:
np.random.rand(3,2)

array([[0.81192786, 0.08705062],
       [0.7723667 , 0.13437163],
       [0.4314016 , 0.94281395]])

In [35]:
x = 10 +2.5*np.random.random(3)
print(x)

[11.54050183 10.33827505 11.10106778]


In [50]:
from io import StringIO
import numpy as np

x = StringIO('''12 23 34 45 56 67 78 89''')

d = np.loadtxt(x,delimiter=' ')
print(d)
c = np.array(d,dtype=np.int64)
print(c)

[12. 23. 34. 45. 56. 67. 78. 89.]
[12 23 34 45 56 67 78 89]


In [53]:
import numpy as np

print(np.array(([1, 2], (3,4))).shape)
print(np.array(([1, 2], (3,4))))

(2, 2)
[[1 2]
 [3 4]]


In [54]:
np.arange(1,10,5)

array([1, 6])

In [55]:
import numpy as np

x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [58]:
np.random.rand(3, 2)

array([[0.0646084 , 0.09843079],
       [0.14768493, 0.62663693],
       [0.23046597, 0.08648905]])

In [73]:
np.random.random((3,2))

array([[0.83871431, 0.63046798],
       [0.78115375, 0.72484868],
       [0.56503152, 0.35254226]])

In [68]:
x= np.array([[[-1,1],[-2,2]],[[-3,3], [-4, 4]]])
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 2, 2)
8


In [24]:
np_vec2

NameError: name 'np_vec2' is not defined

In [86]:
np_vec2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [74]:
a = np.array([1,2,3])
a+1

array([2, 3, 4])

In [75]:
np.sum(a)

6

In [79]:
b = np.array([[1,2,3],[1,2,3]])
print(b.sum(axis=1))
print(b.sum())
print(b.sum(axis=0))

[6 6]
12
[2 4 6]


In [89]:
np.mean(a)

2.0

In [90]:
x = np.random.normal(loc=10.0,scale=2,size=50)
print(x)
print(x.size)
print(x.mean())

[ 9.75760871 11.02037759  9.93064168  8.51601479  7.3459905  10.38939197
 10.27577127 10.1135682  10.14965146  7.97636018  8.42971212  7.0227823
  8.63906638 10.38065996  7.80532246 10.49261157 10.86412318 11.27541567
  9.7592679   8.15625526 11.48612104  8.58549445 13.38398295  7.6877451
 10.10292316  8.76777436  8.56679677 11.81566702 10.91564188  8.94780059
 10.36062954 10.52100762 11.77657803  8.18262879 13.71366107 13.0506605
  8.71916277  8.71772204 11.15300809 13.0276789   7.00291215  8.21124612
  8.15060443  7.65746448  9.61912238 10.40447821 10.72060118 10.62262393
 11.20159519 12.43291169]
50
9.876136751986154


In [5]:
import numpy as np

a1 = np.array([[1,2],[3,4]])
b1 = np.array([[4,3],[2,1]])

a1+b1

array([[5, 5],
       [5, 5]])

In [6]:
a1 * b1

array([[4, 6],
       [6, 4]])

In [93]:
#matrix multiplication
a1.dot(b1)

array([[ 8,  5],
       [20, 13]])

In [7]:
d1 = np.arange(10)

In [95]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
#slicing
d1[1:4]

array([1, 2, 3])

In [98]:
d2 = np.arange(10).reshape(5,2)

In [99]:
d2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [101]:
d2[4,1]

9

In [103]:
: is used for whole row or col
d2[:,0]

array([0, 2, 4, 6, 8])

In [102]:
x = np.arange(4)
print(x.flatten())

[0 1 2 3]


In [104]:
x = np.arange(12).reshape(3,4)
print(x[-1])
print(x[-1:,].shape)

[ 8  9 10 11]
(1, 4)


In [111]:
print(np.repeat(3,4))

[3 3 3 3]


In [106]:
x = np.arange(30).reshape(3,5,2)
print(x[1][::2])

[[10 11]
 [14 15]
 [18 19]]


In [115]:
x = np.arange(4).reshape(2,2)
print(x)
print(x.tolist())
print(np.isfinite(x))

[[0 1]
 [2 3]]
[[0, 1], [2, 3]]
[[ True  True]
 [ True  True]]


In [113]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


**Python**

In [92]:
#for loop w.r.t dimension
x = np.array([[-1, 1], [-2, 2]])

for row in x:
    print('Row :',row)

Row : [-1  1]
Row : [-2  2]


In [93]:
#for loop w.r.t element
x = np.array([[-1, 1], [-2, 2]])

for row in np.nditer(x):
    print('Row :',row)

Row : -1
Row : 1
Row : -2
Row : 2


In [101]:
x = np.arange(1,100,5).reshape(4,5)
print(x)
condition  = x%2 == 0
print(condition)
print(x[condition])

[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 6 16 26 36 46 56 66 76 86 96]


In [105]:
d2[4,1] = 10


In [106]:
d2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8, 10]])

In [118]:
#assignment
divthree = np.arange(9,100,3)
divthree

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [127]:
divnine = []
for a in divthree:
    if a%9 == 0:
        divnine.append(a)
        
divnine  


[9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]

In [129]:
for i in divnine:
    if i != 0:
        cnt = cnt+1
cnt

11

In [133]:
divthree.reshape(31,1)

array([[ 9],
       [12],
       [15],
       [18],
       [21],
       [24],
       [27],
       [30],
       [33],
       [36],
       [39],
       [42],
       [45],
       [48],
       [51],
       [54],
       [57],
       [60],
       [63],
       [66],
       [69],
       [72],
       [75],
       [78],
       [81],
       [84],
       [87],
       [90],
       [93],
       [96],
       [99]])

In [134]:
divthree.max()

99

In [139]:
divthreesec = []
for i in divthree:
    if i == divthree.max():
        break
    else:
        divthreesec.append(i)

div3sec = np.array(divthreesec)
div3sec.max()

96

In [28]:
import numpy as np

Zero_row = np.zeros((1,3))
print(Zero_row)
one_col = np.ones((3,1))
print(one_col)
a = np.array([(1,2,3),(4,5,6)])
b = np.arange(11,20)
print(a)
print(b)

b = b.reshape(3,-1)
print(b)

c = np.vstack((a,b,Zero_row))
print(c)

a = a.reshape(3,2)
print(a)

d = np.hstack((a,b,one_col))
print(d)

e = np.hsplit(d,6)
print(e)
print(e[0])

f = np.hsplit(d,3)
print(f)
print(f[0])

[[0. 0. 0.]]
[[1.]
 [1.]
 [1.]]
[[1 2 3]
 [4 5 6]]
[11 12 13 14 15 16 17 18 19]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]
[array([[1.],
       [3.],
       [5.]]), array([[2.],
       [4.],
       [6.]]), array([[11.],
       [14.],
       [17.]]), array([[12.],
       [15.],
       [18.]]), array([[13.],
       [16.],
       [19.]]), array([[1.],
       [1.],
       [1.]])]
[[1.]
 [3.]
 [5.]]
[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [70]:
x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)
print(x)
print(y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [71]:
np.arange(20).reshape(10, 10)

ValueError: cannot reshape array of size 20 into shape (10,10)

In [72]:
np.arange(90).reshape(3, 15, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79],
        [80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89]]])

In [32]:
base_data = np.arange(100,200,5)
print(base_data)
a = np.array([(1,2),(10,15)])
print(a)
print(base_data[a])
print(base_data[-1]) #gives the last element

print(base_data[a].T)

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]
[[ 1  2]
 [10 15]]
[[105 110]
 [150 175]]
195
[[105 150]
 [110 175]]
